### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by JIzabal** [2680991462/cse15l-lab-reports#1]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
  - Include links to VS Code and OpenSSH downloads for the reader
- [x] All relevant code examples written with backticks (```)
  - Commands, java files, and other code should be written with backticks
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example counts keystrokes and shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by valar23** [comment]
can you be more specific about these two problems?
i don't know the meaning of all relevant URLs written as markdown links

**Comment by JIzabal** [comment]
No problem! For the relevant URLs we want you to use markdown links to add URLs to your markdown file. [Here's](https://ucsd-cse15l-w22.github.io/week/week2/#editing-markdown) a link to the Week 2 lab section that goes over markdown and has some websites that cover the syntax. Then for the other piece of feedback, whenever writing code in a markdown file, it's good practice to use backticks to show to the reader that the text is code. Let me know if you have any more questions, and once you've fixed the issues then submit a regrade request as described above.

**Comment by valar23** [comment]
can you take a look and see if I'm on the right track, since one fail lab report would cause a B....
https://2680991462.github.io/cse15l-lab-reports/lab-report-1-week-2

**Comment by JIzabal** [comment]
No worries! You won't fail as long as you fix the issues described. The URLs look good to me! One other thing you can do for the remote running section is include another bullet point describing how many keystrokes your one command takes versus doing multiple of the same commands. Once you do that, go ahead and send me a regrade request and I'll fix your grade!

**Comment by JIzabal** [comment]
Looks good! Just wanted to point out that after that long command for the last section is written, running it again is only 2 keystrokes (Clicking the up key to go to the previous command and clicking enter to execute the command).
